### ISSUE TITLE
memutils is missing?

### ISSUE THREAD

**Issue by pablomarx** [brianwiddas/pi-baremetal#1]
Both the Makefile and README make reference to memutils.c, but this file doesn't seem to be in master.  framebuffer really seems to want this for the memmove/memclr functions.

**Comment by fkpwolf** [comment]
revert to an old version:  for example

git checkout d8fc2d67b7b87cc8a93b472db73c97eafcd04a52

**Comment by brianwiddas** [comment]
Oops. I missed them from the last commit. They're there now.

Sorry it took so long to spot.
